In [24]:
import os
import pandas as pd
import csv
import numpy as np
import tensorflow as tf

ImportError: No module named tensorflow

In [4]:
home = os.path.expanduser("~")
dataRoot = os.path.join(home, "CS230", "CheXpert-v1.0-small")
os.listdir(dataRoot)

['valid', 'valid.csv', '.DS_Store', 'train', 'train.csv']

In [6]:
# Train dataframe preprocessing
train_df = pd.read_csv(os.path.join(dataRoot, "train.csv"), encoding = "ISO-8859-1")
print(train_df.columns)

Index([u'Path', u'Sex', u'Age', u'Frontal/Lateral', u'AP/PA', u'No Finding',
       u'Enlarged Cardiomediastinum', u'Cardiomegaly', u'Lung Opacity',
       u'Lung Lesion', u'Edema', u'Consolidation', u'Pneumonia',
       u'Atelectasis', u'Pneumothorax', u'Pleural Effusion', u'Pleural Other',
       u'Fracture', u'Support Devices'],
      dtype='object')


In [14]:
# Filtering for Frontal imaging
sub = train_df[train_df["Frontal/Lateral"] == "Frontal"]
# Drop AP/PA
sub = sub.drop(["AP/PA"], axis = 1)
# Convert Unmenttioned to Negatives  i.e. Nah to 0
sub = sub.fillna(0)
# Convert Uncertain to Positive i.e. -1 to 1
sub = sub.replace(-1, 1)

print(sub)


                                                     Path     Sex  Age  \
0       CheXpert-v1.0-small/train/patient00001/study1/...  Female   68   
1       CheXpert-v1.0-small/train/patient00002/study2/...  Female   87   
2       CheXpert-v1.0-small/train/patient00002/study1/...  Female   83   
4       CheXpert-v1.0-small/train/patient00003/study1/...    Male   41   
5       CheXpert-v1.0-small/train/patient00004/study1/...  Female   20   
7       CheXpert-v1.0-small/train/patient00005/study1/...    Male   33   
9       CheXpert-v1.0-small/train/patient00005/study2/...    Male   33   
10      CheXpert-v1.0-small/train/patient00005/study2/...    Male   33   
11      CheXpert-v1.0-small/train/patient00006/study1/...  Female   42   
12      CheXpert-v1.0-small/train/patient00007/study1/...    Male   69   
13      CheXpert-v1.0-small/train/patient00007/study2/...    Male   69   
14      CheXpert-v1.0-small/train/patient00008/study1/...    Male   81   
15      CheXpert-v1.0-small/train/pati

In [16]:
# Pull cols to form y_train
cols = ["No Finding","Enlarged Cardiomediastinum","Cardiomegaly","Lung Opacity","Lung Lesion","Edema","Consolidation","Pneumonia","Atelectasis","Pneumothorax","Pleural Effusion","Pleural Other","Fracture","Support Devices"] #...
y_train = sub[cols]


In [18]:
# Form X_train
N = y_train.shape[0]
H = 
W =
D = 1
X = np.zeros((N,H,W,D))

# iterrows()?
# Iterate through each row, pull the image from the path, and pass into X

191027


NameError: name 'H' is not defined

In [1]:
import numpy as np

In [3]:
a = np.random.randn(3,3)
b = np.random.randn(3,3)

In [4]:
print(a)
print(b)

[[-0.98982981 -1.58114807 -1.24315967]
 [ 0.17497381 -0.9383617   0.86294574]
 [ 0.16147693 -1.17842499 -1.81553927]]
[[ 2.16334634  0.74060063  0.8665509 ]
 [ 0.99688436 -0.89379969  0.6075082 ]
 [ 0.3385079   0.22130206  0.3750875 ]]


In [5]:
c = np.dot(a,b)

In [ ]:
print(c)